cache = "cache.json"
media_dir = "./media"
media_extensions = [
    "avi",
    "flv",
    "gif",
    "jpeg",
    "jpg",
    "heic",
    "m4v",
    "mkv",
    "mov",
    "mp4",
    "mpeg",
    "mpg",
    "png",
    "webm",
    "wmv",
    "bmp",
]
ignore_files_with = ["$", "System"]

[logging]
console_logging_level = "DEBUG"
file_logging_level = "DEBUG"
logs_folder_path = "Logs"
use_logs_folder = true
number_of_logs_to_keep = 10
log_message_format = "%(asctime)s.%(msecs)03d %(levelname)s [%(funcName)s]: %(message)s"
